# Site settings
email: gabrielchen001@gmail.com 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Shadows
description: The Face of Moon is Always in Shadows.
url: "https://gabrielchen0.github.io"
twitter_username: 
default_img:  

# Profile settings
name: Benjamin 
profile_img: http://i.imgur.com/NyDNUWc.jpg
profile: I guess, there is no one could live in shadows, but the face of Moon is always in shadows.   
social:
    github: https://github.com/gabrielchen0 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
